version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
  settings:
    errcheck:
      check-type-assertions: false
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
